name: sganalysis
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - pandas
  - seaborn
  - tifffile
  - nd2reader
  - pytorch
  - pytorch-gpu
  - torchvision
  - torchaudio
  - cellpose
  - edt
  - ipykernel
  - numba
  