name: sganalysis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - pandas
  - seaborn
  - tifffile
  - nd2reader
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=12.1 # Change to match your GPU/CUDA version
  - pip
  - pip:
      - cellpose<=3
      - edt